<?php
	$result = array();
	
	include 'conn.php';
	
	$rs = mysql_query("SELECT CONS_ID, 
	CONS_DESCRIPCION,  
	CONCAT (CONS_FEC_GEN_DES,' HASTA ', CONS_FEC_GEN_HAS) AS FEC_GEN, 
	CONCAT (CONS_FEC_VEN_DES,' HASTA ', CONS_FEC_VEN_HAS) AS FEC_VEN, 
	CONCAT (CONS_FEC_CON_DES,' HASTA ', CONS_FEC_CON_HAS) AS FEC_CONS, 
	CONCAT (CONS_FEC_PRE_DES,' HASTA ', CONS_FEC_PRE_HAS) AS FEC_PRE, 
	CASE WHEN CONS_PER = 1 THEN 'MENSUAL' WHEN CONS_PER=2 THEN 'BIMENSUAL' WHEN CONS_PER=3 THEN 'TRIMESTRAL' WHEN CONS_PER=6 THEN 'SEMESTRAL' WHEN CONS_PER=12 THEN 'ANUAL' WHEN CONS_PER=60 THEN 'QUINQUENIO' END CONS_PER, 
	CASE WHEN CONS_UNI_PRE = 1 THEN 'MILES' WHEN CONS_UNI_PRE = 1000 THEN 'PESOS' WHEN CONS_UNI_PRE = 0.001 THEN 'MILLONES' END CONS_UNI_PRE
	, CONS_RIT_VEN, 
	CONS_POR_VTA_NHO, CONS_VER, 
	CONS_IND_ID_REE,
	CONS_IND_FECHA_REE, 
	CONS_IND_VALOR_REE,
	CASE WHEN (FA_RITMO_VENTAS_CBX) = '*' THEN 'TODOS' ELSE 
		(CONCAT(CASE 
		WHEN FA_RITMO_VENTAS_CBX = '>' THEN 'MAYOR' 
		WHEN FA_RITMO_VENTAS_CBX = '<' THEN 'MENOR' 
		WHEN FA_RITMO_VENTAS_CBX ='==' THEN 'IGUAL QUE'
		WHEN FA_RITMO_VENTAS_CBX ='<>' THEN 'ENTRE' END,' ', FA_RITMO_VENTAS_DESDE,' ', FA_RITMO_VENTAS_HASTA) ) END RIT_VEN,
	
	CASE WHEN (FA_VLVND_COSTO_DIRECTO_CBX) = '*' THEN 'TODOS' ELSE 
		(CONCAT(CASE 
		WHEN FA_VLVND_COSTO_DIRECTO_CBX = '>' THEN 'MAYOR' 
		WHEN FA_VLVND_COSTO_DIRECTO_CBX = '<' THEN 'MENOR' 
		WHEN FA_VLVND_COSTO_DIRECTO_CBX ='==' THEN 'IGUAL QUE'
		WHEN FA_VLVND_COSTO_DIRECTO_CBX ='<>' THEN 'ENTRE' END,' ', FA_VLVND_COSTO_DIRECTO_DESDE,' ', FA_VLVND_COSTO_DIRECTO_HASTA) ) END COS_DIR,
	
	CASE WHEN (FA_VLVND_VENTAS_CBX) = '*' THEN 'TODOS' ELSE 
		(CONCAT(CASE 
		WHEN FA_VLVND_VENTAS_CBX = '>' THEN 'MAYOR' 
		WHEN FA_VLVND_VENTAS_CBX = '<' THEN 'MENOR' 
		WHEN FA_VLVND_VENTAS_CBX ='==' THEN 'IGUAL QUE'
		WHEN FA_VLVND_VENTAS_CBX ='<>' THEN 'ENTRE' END,' ', FA_VLVND_VENTAS_DESDE,' ', FA_VLVND_VENTAS_HASTA) ) END VAL_VENT,
	
	CASE WHEN (FA_VL_UN_COSTO_VENTAS_CBX) = '*' THEN 'TODOS' ELSE 
		(CONCAT(CASE 
		WHEN FA_VL_UN_COSTO_VENTAS_CBX = '>' THEN 'MAYOR' 
		WHEN FA_VL_UN_COSTO_VENTAS_CBX = '<' THEN 'MENOR' 
		WHEN FA_VL_UN_COSTO_VENTAS_CBX ='==' THEN 'IGUAL QUE'
		WHEN FA_VL_UN_COSTO_VENTAS_CBX ='<>' THEN 'ENTRE' END,' ', FA_VL_UN_COSTO_VENTAS_DESDE,' ', FA_VL_UN_COSTO_VENTAS_HASTA) ) END VL_COS_VENT,
	
	CASE WHEN (FA_COSTO_VENTAS_CBX) = '*' THEN 'TODOS' ELSE 
		(CONCAT(CASE 
		WHEN FA_COSTO_VENTAS_CBX = '>' THEN 'MAYOR' 
		WHEN FA_COSTO_VENTAS_CBX = '<' THEN 'MENOR' 
		WHEN FA_COSTO_VENTAS_CBX ='==' THEN 'IGUAL QUE'
		WHEN FA_COSTO_VENTAS_CBX ='<>' THEN 'ENTRE' END,' ', FA_COSTO_VENTAS_DESDE,' ', FA_COSTO_VENTAS_HASTA) ) END COS_VEN,
	
	
	CASE WHEN (FA_PAIS) = '*' THEN 'TODOS' ELSE FA_PAIS END FA_PAIS, 
	CASE WHEN (FA_CIUDAD) = '*'  THEN 'TODOS' ELSE FA_CIUDAD END FA_CIUDAD, 
	CASE WHEN (FA_SEGMENTO) = '*' THEN 'TODOS' ELSE FA_SEGMENTO END FA_SEGMENTO, 
	CASE WHEN (FA_PARTICIPACION) = '*' THEN 'TODOS' ELSE FA_PARTICIPACION END FA_PARTICIPACION
  FROM tb_consolidados      
  LEFT JOIN tb_filtro_avanzado ON CONS_ID = FA_CONS
	
	");
	
	
	
	$items = array();
	while($row = mysql_fetch_object($rs)){
		array_push($items, $row);
	}
	
	echo json_encode($items);
?>