<?php
	$result = array();
	
	include 'conn.php';
	
	$rs = mysql_query("SELECT CONS_ID, 
	CONS_DESCRIPCION, CONS_FEC_GEN_DES, 
	CONS_FEC_GEN_HAS, CONS_FEC_VEN_DES, 
	CONS_FEC_VEN_HAS, CONS_FEC_CON_DES, 
	CONS_FEC_CON_HAS, CONS_FEC_PRE_DES, 
	CONS_FEC_PRE_HAS, 
	CASE WHEN CONS_PER = 1 THEN 'MENSUAL' WHEN CONS_PER=2 THEN 'BIMENSUAL' WHEN CONS_PER=3 THEN 'TRIMESTRAL' WHEN CONS_PER=6 THEN 'SEMESTRAL' WHEN CONS_PER=12 THEN 'ANUAL' WHEN CONS_PER=60 THEN 'QUINQUENIO' END CONS_PER, 
	CASE WHEN CONS_UNI_PRE = 1 THEN 'MILES' WHEN CONS_UNI_PRE = 1000 THEN 'PESOS' WHEN CONS_UNI_PRE = 0.001 THEN 'MILLONES' END CONS_UNI_PRE
	, CONS_RIT_VEN, 
	CONS_POR_VTA_NHO, CONS_VER, 
	CONS_IND_ID_REE,
	CONS_IND_FECHA_REE, 
	CONS_IND_VALOR_REE
	FROM tb_consolidados WHERE  CONS_CONS = 'S'");
	
	$items = array();
	while($row = mysql_fetch_object($rs)){
		array_push($items, $row);
	}
	
	echo json_encode($items);
?>